# variables

# screenlock
# use hyprlock
$locker_name = hyprlock
$locker_cmd = $locker_name
# use swaylock
# $locker_name = swaylock
# $locker_cmd = $locker_name -f -c 000000

# dpms
$dpms_off = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'
$dpms_on  = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'


# keyboard daemon
$kb_daemon_pause = ~/.config/kanata/local/kanata-toggle.sh pause
$kb_daemon_resume = ~/.config/kanata/local/kanata-toggle.sh resume

general {
  # 0: disable 1: normal 2: auto 3: lock notify
  inhibit_sleep = 2
  lock_cmd = $kb_daemon_pause; (pidof $locker_name || $locker_cmd); $kb_daemon_resume
  unlock_cmd = $kb_daemon_resume
  before_sleep_cmd = loginctl lock-session
  after_sleep_cmd = $dpms_on
}

listener {
  # dim the screen
  timeout = 293
  on-timeout = busctl --user -- set-property rs.wl-gammarelay / rs.wl.gammarelay Brightness d .3
  on-resume  = busctl --user -- set-property rs.wl-gammarelay / rs.wl.gammarelay Brightness d 1
}

# listener {
#   # monitor backlight
#   timeout =297
#   on-timeout = brightnessctl -s set 10         # set monitor backlight to minimum, avoid 0 on OLED monitor.
#   on-resume = brightnessctl -r                 # monitor backlight restore.
# }

# Lock at 5 minutes
listener {
  timeout = 300
  on-timeout = loginctl lock-session
}

# Turn off screen at 5 minutes and 5 seconds
listener {
  timeout = 305
  on-timeout = $dpms_off
  on-resume  = $dpms_on

}

# listener {
#   timeout = 365
#   on-timeout = sudo /usr/bin/systemctl suspend
# }
# listener {
#   timeout = 425
#   #on-timeout = sudo /usr/bin/systemctl hibernate
#   on-timeout = sudo /usr/bin/systemctl hybrid-sleep
# }
